"""initial state

Revision ID: 00000000001
Revises: 
Create Date: 2020-04-19 15:00:45.144060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00000000001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("tag_id"),
    )
    op.create_table(
        "posts",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("short", sa.Text(), nullable=True),
        sa.Column("full", sa.Text(), nullable=False),
        sa.Column("picture", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("post_id"),
    )
    op.create_table(
        "posts_to_tags",
        sa.Column("posts", sa.Integer(), nullable=True),
        sa.Column("tags", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["tags"], ["tags.tag_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["posts"], ["posts.post_id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts_to_tags")
    op.drop_table("posts")
    op.drop_table("tags")
    # ### end Alembic commands ###
